### ISSUE TITLE
xsbench-cl does not seem to be latest version

### ISSUE THREAD

**Issue by Sartek** [AMDComputeLibraries/ComputeApps#2]
I noticed the readme in xsbench-cl tell you to get the latest version from here https://github.com/ANL-CESAR/XSBench 
as well as in xsbench-amp
xsbench-cl is version 10 while xsbench-amp is version 13
the XSBench is version 13
it also only lists 1 development lead instead of 3 in both the cl and amp folder readmes.

Could the difference be explained or fixed if this is a mistake.

**Comment by ztschir** [comment]
Hey Sartek,

Referring to the xsbench-cl version, when we ported the code over to an OpenCL environment, it was at a time when version 10 was the most current version. Since the code diverged so far from the original source, bringing any changes from version 13 into the OpenCL implementation would not make since, especially since the changes were mostly cosmetic. We can open this up as a separate issue and assign a lower priority. 

I will put in a request to update both README files to reflect the most current commit on the ANL repo: https://github.com/ANL-CESAR/XSBench/commit/90e13329c27b87503a5f7fce611e4ee61a865a70
